---
- name: Sample login  and logout playbook
  hosts: demo_netscalers

  gather_facts: false

  tasks:
    - name: V2 | Sample Task | login
      delegate_to: localhost
      register: login_result
      netscaler.adc.login:
        # nsip: 10.0.0.1 # This can also be given via NETSCALER_NSIP environment variable
        # nitro_protocol: https # This can also be given via NETSCALER_NITRO_PROTOCOL environment variable
        # validate_certs: false # This can also be given via NETSCALER_VALIDATE_CERTS environment variable
        # save_config: false # This can also be given via NETSCALER_SAVE_CONFIG environment variable

        username: nsroot
        password: verysecretpassword

    - name: Print login sessionid
      ansible.builtin.debug:
        var: login_result.sessionid

    - name: V2 | Sample Task | nsip
      delegate_to: localhost
      netscaler.adc.nsip:
        nitro_auth_token: "{{ login_result.sessionid }}" # This can also be given via NETSCALER_NITRO_AUTH_TOKEN environment variable
        # nsip: 10.0.0.1 # This can also be given via NETSCALER_NSIP environment variable
        # nitro_protocol: https # This can also be given via NETSCALER_NITRO_PROTOCOL environment variable
        # validate_certs: false # This can also be given via NETSCALER_VALIDATE_CERTS environment variable
        # save_config: false # This can also be given via NETSCALER_SAVE_CONFIG environment variable

        state: present

        ipaddress: 4.4.4.4
        netmask: 255.255.255.192
        type: VIP

    - name: V2 | Sample Task | logout
      delegate_to: localhost
      netscaler.adc.logout:
        nitro_auth_token: "{{ login_result.sessionid }}" # This can also be given via NETSCALER_NITRO_AUTH_TOKEN environment variable
        # nsip: 10.0.0.1 # This can also be given via NETSCALER_NSIP environment variable
        # nitro_protocol: https # This can also be given via NETSCALER_NITRO_PROTOCOL environment variable
        # validate_certs: false # This can also be given via NETSCALER_VALIDATE_CERTS environment variable
        # save_config: false # This can also be given via NETSCALER_SAVE_CONFIG environment variable
